name: Restore Repository

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      record_id:
        description: 'Record ID'
        required: true

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Repository
        uses: berkayy-atas/marketplace-test-workflow-restore@v1.0.20
        with:
          activation_code: ${{ secrets.ACTIVATION_CODE }}
          encryption_key: ${{ secrets.ENCRYPTION_KEY }}
          record_id: ${{ github.event.inputs.RECORD_ID }}
