name: Restore Repository

permissions:
  id-token: write         # ← OIDC token’ı için
  contents: write
  pull-requests: write
  issues: write
  checks: write
  actions: write    

on:
  workflow_dispatch:
    inputs:
      record_id:
        description: 'Record ID'
        required: true

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Repository
        uses: berkayy-atas/marketplace-test-workflow-restore@v1.0.20
        with:
          activation_code: ${{ secrets.ACTIVATION_CODE }}
          encryption_key: ${{ secrets.ENCRYPTION_KEY }}
          record_id: ${{ github.event.inputs.RECORD_ID }}
